apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-content-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hajle-silesia/file-content-monitor-config.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
