apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: strimzi-kafka-operator
      repoURL: https://strimzi.io/charts/
      targetRevision: 0.45.0
      helm:
        releaseName: strimzi
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: event-streaming
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
