apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/hajle-silesia/event-streaming-ui-config.git
      targetRevision: HEAD
      ref: values
    - chart: kafka-ui
      repoURL: https://provectus.github.io/kafka-ui-charts
      targetRevision: 0.7.6
      helm:
        releaseName: kafka-ui
        valueFiles:
          - $values/helm/values.yaml
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: event-streaming
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
