apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.8.3
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/helm/values.yaml
    - repoURL: https://github.com/hajle-silesia/external-secrets-config.git
      targetRevision: HEAD
      path: helm/templates
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
