apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-streaming
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/hajle-silesia/video-streaming-config.git
      targetRevision: 0.0.0
      chart: video-streaming-config
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
