apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-streaming-ui-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hajle-silesia/event-streaming-ui-config.git
    targetRevision: HEAD
    path: helm
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: event-streaming
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
