apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kafka-ui
    repoURL: https://provectus.github.io/kafka-ui
    targetRevision: 0.6.2
    helm:
      releaseName: kafka-ui
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: event-streaming
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
