apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-content-processor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/hajlesilesia
    targetRevision: HEAD
    chart: file-content-processor-config
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
