apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-workload-identity-federation-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: gcp-workload-identity-federation-webhook
      repoURL: https://pfnet-research.github.io/gcp-workload-identity-federation-webhook
      targetRevision: 0.3.2
      helm:
        releaseName: gcp-workload-identity-federation-webhook
        valueFiles:
          - $values/helm/values.yaml
    - repoURL: https://github.com/hajle-silesia/gcp-workload-identity-federation-webhook-config.git
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: gcp-wif-webhook-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
